/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEE = 5;
  /** RegularExpression Id. */
  int THE = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int IS = 8;
  /** RegularExpression Id. */
  int ARE = 9;
  /** RegularExpression Id. */
  int NORTH = 10;
  /** RegularExpression Id. */
  int SOUTH = 11;
  /** RegularExpression Id. */
  int EAST = 12;
  /** RegularExpression Id. */
  int WEST = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int SEP = 15;
  /** RegularExpression Id. */
  int MEAS = 16;
  /** RegularExpression Id. */
  int DIS = 17;
  /** RegularExpression Id. */
  int LOC = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"i see\"",
    "\"the\"",
    "\"and\"",
    "\"is\"",
    "\"are\"",
    "\"north of\"",
    "\"south of\"",
    "\"east of\"",
    "\"west of\"",
    "<END>",
    "\",\"",
    "<MEAS>",
    "<DIS>",
    "<LOC>",
    "\"[\"",
    "\"]\"",
  };

}
